spring:
  application:
    name: qa-web
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
  redis:
    database: 0
    host: 10.10.6.7
    port: 6379
    timeout: 1000
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0

logging:
  level:
    com.okjiaoyu.auto.dao: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.okjiaoyu.auto.vo
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
